### ISSUE TITLE
Failed to convert ONNX to CoreML

### ISSUE THREAD

**Issue by hlstwizard** [isty2e/KataGoONNX#1]
Thanks for sharing this converter, I'm trying to convert katago model to coreml as quite a few people doing now.

I can use the converter in this repo to convert Katago bin file to ONNX and it could be loaded successully in pytorch.

However,

* I'm not sure how to validate the converting is successful or not
* converting the onnx model to coreml using coreml 4.0 raising this exception

``` bash
1/284: Converting Node Type Slice
Traceback (most recent call last):
  File "convert.py", line 12, in <module>
    new_model = ct.converters.onnx.convert(model)
  File "/Users/huangyiming/opt/miniconda3/envs/katago/lib/python3.7/site-packages/coremltools/converters/onnx/_converter.py", line 743, in convert
    _convert_node(builder, node, graph, err)
  File "/Users/huangyiming/opt/miniconda3/envs/katago/lib/python3.7/site-packages/coremltools/converters/onnx/_operators.py", line 2670, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/Users/huangyiming/opt/miniconda3/envs/katago/lib/python3.7/site-packages/coremltools/converters/onnx/_operators.py", line 1909, in _convert_slice
    starts = node.attrs["starts"]
KeyError: 'starts'
```
I know this might be an issue with coreml converter, is there any direction to look for ? is it because of Katago model version v8 vs v10?

**Comment by hlstwizard** [comment]
Just read https://coremltools.readme.io/docs/onnx-conversion

It seems that it is not maintained well, and will be deprecated.

Is it possible to write a similar converter of tensorflow? I think the file structure of katago bin will be very helpful.
I would like to work on it, guidence will be much appreciated!

**Comment by isty2e** [comment]
There are already some TF to ONNX converters out there. But after trying some of them, I didn't like the messy structure of the converted .onnx files, especially concerning NCHW/NHWC stuff. That's why I decided to write this converter in the first place.

Regarding the structure of .bin file, https://github.com/isty2e/KataGoONNX/blob/master/netparser.py#L328 can be a bit helpful, and reading the original KataGo source code, of course. Note that this converter is for v8 networks only, and there are some additions in the v10 format.
